#!/bin/bash

# shellcheck source=meta-facebook/meta-harma/recipes-phosphor/state/phosphor-state-manager/power-cmd
source /usr/libexec/phosphor-state-manager/power-cmd

# Check SGPIO validity
if ! check_valid_sgpio; then
    echo "SGPIO invalid, skipping power good deassertion"
    exit 0
fi

# Sync Led status to on
systemctl start obmc-led-group-start@power_on.service


# Checking and Syncing power policy.
# Get current host state
current_state=$(busctl get-property \
    xyz.openbmc_project.State.Host0 \
    /xyz/openbmc_project/state/host0 \
    xyz.openbmc_project.State.Host \
    CurrentHostState | awk '{print $2}' | tr -d '"')

# Exit if host is already transitioning to running
if [ "$current_state" = "xyz.openbmc_project.State.Host.HostState.TransitioningToRunning" ]; then
    echo "Host is transitioning to running, skipping power good deassertion"
    exit 0
fi

# List of services that block power_on_sync
block_services=(
    host-poweron@0.service
    host-powerreset@0.service
)

# Check each service's state
for svc in "${block_services[@]}"; do
    # Get the detailed SubState (e.g., running, exited, dead)
    substate=$(systemctl show -p SubState --value "$svc")
    # Get the general ActiveState (e.g., active, inactive, activating)
    active_state=$(systemctl is-active "$svc")

    # LOGIC: Block if the service is neither "inactive" nor "exited"
    # This effectively blocks "running", "activating", and "deactivating"
    if [ "$active_state" != "inactive" ] && [ "$substate" != "exited" ]; then
        echo "Blocking service $svc is busy ($active_state/$substate), skipping process"
        exit 0
    fi
done

# Safe to power on
# Wait 3 seconds, checking every second
power_on_sync 3 1

exit 0
